jdbc:
  url: jdbc:mysql://xxxxx:13306/fqdoc?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&nullCatalogMeansCurrent=true
  user: xxxx
  password : xxxx
  keywordSql: 
  stopWordSql: 
